### ISSUE TITLE
Permission to use

### ISSUE THREAD

**Issue by rhyst** [fjebaker/vscode-metapost#6]
Firstly thank you for putting together this language definition. 

I would like to include a definition based on this in an extension that I maintain (https://github.com/rhyst/vscode-therion-language) but I would like to get your permission first. I will include attribution and a link to this repository in the syntax file and in the README of the extension.

The reason I would like to include it directly (rather than `include`-ing it like you do with latex) is that I need to make some modifications that are specific to metapost snippets that are used in Therion (which I believe does some preprocessing).

Thanks again 😊

**Comment by fjebaker** [comment]
Hi @rhyst -- yeah, that's absolutely no problem! You've made me aware I forgot to add a license to this repository. I'll add MIT, as that should be compatible with anything you (or others) may wish to do.

Thanks for asking for permission! Consider it completely granted :)

**Comment by rhyst** [comment]
Brilliant, thank you very much 🙇
