### ISSUE TITLE
Preview in vscode

### ISSUE THREAD

**Issue by blueeyesblue** [fjebaker/vscode-metapost#8]
Please help to tell how to preview the mp code result to the side. Thank you.

**Comment by fjebaker** [comment]
Hi @blueeyesblue! If you open the command pallette in VSCode (e.g., `Cmd + Shift + P` on Mac), and type "Metapost" you should see all of the exported commands. To preview

- open the MP file you want to preview (it must have at least one `beginfig`)
- in the command pallette, select "Metapost: Preview to the Side"
- select the figure you want to preview from the interactive dialog

The preview should then automatically update whenever you save the source file.

**Comment by blueeyesblue** [comment]
> VSCode (e.g., `Cmd + Shift + P` on Mac)

Thank you for helping me open and see the preview window.

But how to run it? I am running the code from [MetaPost Examples](http://matagalatlante.org/nobre/down/featpost/MPexamples.html):  [A131.mp ](http://matagalatlante.org/nobre/down/featpost/MPexamples.html#:~:text=38.mp-,A131.mp,-acmaglev.mp) which has the beginfig(1).  I tried to run `Metapost: Run` but it had no response.

Thanks you.

**Comment by fjebaker** [comment]
"Metapost: Run" just runs mpost with that file as the arguments -- you should see the output in the file's directory!

**Comment by qwes123** [comment]
![~MY{YO8KD33K099$LD~9GQ6](https://user-images.githubusercontent.com/32217879/178150213-024d07b2-8a86-47e7-91f2-1573ee6260f1.png)
Please help to tell me why my preview window goes wrong like this and how to deal with it. Really thank you.

**Comment by fjebaker** [comment]
Hi @qwes123 -- you'll have to change `filenametemplate` to output either `.png` or `.svg`, since the preview is actually just HTML that gets rendered.

Hopefully that fixes it for you!

**Comment by fjebaker** [comment]
For posterity: a limitation of the preview is that the output file _must be a PNG or SVG_ to work. In order to achieve this, one **must** set the `outputformat` variable, e.g.

```metapost
outputformat:="svg";
outputtemplate:="%j%c." & outputformat;
```

Simply changing suffix in `outputtemplate` is not sufficient to actually change the filetype.
