### ISSUE TITLE
Expand the coverage of keywords and operators

### ISSUE THREAD

**Issue by santhoshtr** [fjebaker/vscode-metapost#9]
Hi,
Could you please expand the supported tokens for keywords and operators by syncing it with the Atom Syntax for metapost available [here](https://archive.softwareheritage.org/browse/content/sha1_git:e1622629a56b0e2360190c23909db59e2f16656a/?origin_url=https://github.com/freebroccolo/atom-language-metapost&path=grammars/metapost.cson)?
Thanks in advance

**Comment by fjebaker** [comment]
Hi @santhoshtr! Wow, thanks for the link to that repository, that somehow flew entirely under my radar! I will sync the wordlists ~later today :)~ as soon as I can!

**Comment by santhoshtr** [comment]
Hi, a gentle ping :-)

**Comment by santhoshtr** [comment]
Thank you.
